# Generated by Django 2.0.9 on 2018-11-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20181108_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
