# Generated by Django 2.0.9 on 2018-11-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20181108_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.PositiveIntegerField(),
        ),
    ]
