# Generated by Django 2.0.9 on 2018-11-10 03:10

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20181109_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
