# Generated by Django 2.0.9 on 2018-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20181109_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
