# Generated by Django 2.0.9 on 2018-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20181110_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
