# Generated by Django 2.0.9 on 2018-11-12 01:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0007_alumno_terminado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='responsable',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='password',
        ),
        migrations.AddField(
            model_name='responsable',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
