# Generated by Django 2.0.9 on 2018-11-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_auto_20181112_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'responsable', 'verbose_name_plural': 'responsables'},
        ),
    ]
