# Generated by Django 2.0.9 on 2019-05-22 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20181112_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.BigIntegerField(default=2000160000, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1936000000)]),
        ),
    ]
