# Generated by Django 2.0.9 on 2018-11-06 02:53
from django.db import migrations, models
from django.core.management import call_command

fixture = "tipoactividad"

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='actividades') 

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('IV', 'Inquietudes vocacionales'), ('CF', 'Complementarias a la formación'), ('EP', 'Enfásis en la profesión'), ('PE', 'Proyectos especiales')], max_length=2)),
                ('horasRequeridas', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.RunPython(load_fixture),
    ]
