# Generated by Django 2.0.9 on 2018-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('C1', 'Cat1'), ('C2', 'Cat2'), ('C3', 'Cat3')], max_length=2)),
                ('valorHoras', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
