# Generated by Django 2.0.9 on 2018-11-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoActividad')),
            ],
        ),
    ]
