# Generated by Django 2.0.9 on 2018-11-07 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('actividades', '0002_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='alumno',
            field=models.ForeignKey(default=2016601609, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno'),
            preserve_default=False,
        ),
    ]
