# Generated by Django 2.0.9 on 2018-11-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20181108_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoactividad',
            name='valorHoras',
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='horasRequeridas',
            field=models.PositiveIntegerField(default=14),
            preserve_default=False,
        ),
    ]
