# Generated by Django 2.0.9 on 2018-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditorio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('validado', models.BooleanField()),
                ('responsables', models.ManyToManyField(to='alumnos.Responsable')),
            ],
        ),
    ]
