# Generated by Django 2.0.9 on 2018-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20181108_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditorio',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
