# Generated by Django 2.0.9 on 2018-11-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20181110_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditorio',
            name='nombre',
            field=models.CharField(default='Evento 1', max_length=200),
            preserve_default=False,
        ),
    ]
