# Generated by Django 2.0.9 on 2018-11-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20181112_0137'),
        ('eventos', '0004_eventoauditorio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditorio',
            name='asistentes',
            field=models.ManyToManyField(to='alumnos.Alumno'),
        ),
    ]
