# Generated by Django 2.0.9 on 2018-11-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_eventoauditorio_asistentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditorio',
            name='asistentes',
            field=models.ManyToManyField(blank=True, to='alumnos.Alumno'),
        ),
    ]
