# Generated by Django 2.0.9 on 2019-06-02 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20181115_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditorio',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(regex="^([A-Za-zÁÉÍÓÚñáéíóúÑ]{0}?[A-Za-zÁÉÍÓÚñáéíóúÑ\\'])+[\\s]?([A-Za-zÁÉÍÓÚñáéíóúÑ]{0}?[A-Za-zÁÉÍÓÚñáéíóúÑ\\'])?$")]),
        ),
    ]
